# Generated by Django 5.2.17 on 2026-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('pontos', models.IntegerField()),
                ('fase_alcancada', models.IntegerField()),
                ('tempo_segundos', models.FloatField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pontos', 'tempo_segundos'],
            },
        ),
    ]
